# config.sh — SAF, 2dSFS and Fst Pipeline
# Edit all paths below before running
# =============================================================================

# Software
# ANGSD executable directory
PROG_ANGSD="/path/to/angsd"
# realSFS executable (in ANGSD misc/)              
PROG_REALSFS="$PROG_ANGSD/misc/realSFS"

# Directories
WD="/path/to/working/directory"
BAM_DIR="$WD/bam_sorted"                        	# sorted BAM files (01.mapping output)
BAM_LIST="${PIPELINE_ROOT}/01.mapping/data/bam.list"	# Full BAM list from 01.mapping (188 individuals)
OUT_BAMLISTS="$WD/bamlists"                		# population-specific BAM lists
OUT_SAF="$WD/saf"                               	# SAF output directory
OUT_2DSFS="$WD/2dSFS"                           	# 2dSFS output directory
OUT_FST="$WD/fst"                               	# Fst output directory
OUT_PLOTS="$WD/fst/plots"                       	# figure output directory

# Shared input files
# Population list shared from 02.genotype_likelihoods
POP_LIST="${PIPELINE_ROOT}/02.genotype_likelihoods/data/pop.list"
# Inbreeding coefficients from 04.inbreeding (one value per individual per population)
OUT_INBREEDING="$WD/inbreeding"                       # directory containing per-population .indF files

# Reference genome
REF_GENOME="/path/to/refgenome/directory"       # used as both -ref and -anc
                                                # Cuevas-Caballé et al. (2021)
                                                # BioProject: PRJNA780920

# Pairs file (generated by 02_prepare_pop_pairs.sh)
PAIRS_FILE="$WD/pop_pairs.txt"

# ANGSD SAF parameters
GL=1                    # SAMtools genotype likelihood model
DO_SAF=2                # calculate SAF using inbreeding coefficients (-indF)
                        # doSaf 2 incorporates individual inbreeding coefficients into the SAF calculation
DO_MAJOR_MINOR=1
DO_MAF=1
DO_POST=1               # calculate posterior probabilities
SAF_THREADS=40          # threads per SAF job (match --cpus-per-task)

# realSFS 2dSFS parameters
FOLD=1                  # fold SFS (use folded spectrum as ancestral allele unknown)
SFS_THREADS=40          # threads for realSFS (match --cpus-per-task)

# Fst parameters
WHICH_FST=1             # Fst estimator: 1 (Bhatia et al., 2013)
FST_THREADS=40          # threads for Fst (match --cpus-per-task)
BOOTSTRAP=100           # bootstrap replicates for confidence intervals
WINDOW=50000            # sliding window size for bootstrap (bp)
STEP=50000              # sliding window step size (bp)

# OpenMP threads for realSFS (must match SFS_THREADS)
export OMP_NUM_THREADS=$SFS_THREADS
